### ISSUE TITLE
Return GRanges for *Assay method

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/RaggedExperiment#16]
From Vince @vjcitn:
Just wondering whether you would consider returning a GRanges
for the *Assay methods, perhaps optionally?  I will be parsing the
rownames to create this for compactAssay.  Probably completely
trivial for sparseAssay as the RaggedExperiment GRanges is
immediately available.

cc: @mtmorgan

**Comment by mtmorgan** [comment]
is this what `as(x, "GRangesList")` accomplishes?

**Comment by vjcitn** [comment]
Looks plausible.  I missed that, but it makes perfect sense.

**Comment by LiNk-NY** [comment]
Hi Vince, @vjcitn 

Does this resolve the issue? 
If it doesn't, please reopen the issue. 

Regards,
Marcel
