### ISSUE TITLE
qreduceSummarizedExperiment vs qreduceAssay argument names

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/RaggedExperiment#19]
I was surprised that qreduceSummarizedExperiment has a different argument (simplify) than the corresponding argument of qreduceAssay (simplifyReduce). Shouldn't these functions have consistent argument names?

**Comment by lwaldron** [comment]
Same comment for the simplifyReduce / simplify arguments to disjoinAssay / disjoinSummarizedExperiment.

**Comment by LiNk-NY** [comment]
Yes, they should. I'll open up an issue at Bioconductor/RaggedExperiment. Thanks.

**Comment by LiNk-NY** [comment]
Thanks. I'll work on a fix for this.

**Comment by LiNk-NY** [comment]
Fixed in 96161709e569639b899b8d2de56d6e735006fe94
