### ISSUE TITLE
unclear documentation of qreduceAssay

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/RaggedExperiment#5]
Arguments given at the top of `?qreduceAssay`:
```
qreduceAssay(x, query, simplify, i = 1, withDimnames = TRUE,
  background = NA)
```
but further below it says:
`qreduceAssay: A function accepting arguments score, range, and qrange:`

**Comment by mtmorgan** [comment]
This is meant to be describing the definition of `simplify` when used in `qreduceAssay()`; the indentation implies this when the help is viewed as plain text; how are you viewing the help page?

**Comment by lwaldron** [comment]
It's indented correctly to be a part of `simplify` (in RStudio). What I didn't get (and still am not sure I get) is that the `simplify` argument of `qreduceAssay` is a *function of two functions*, `disjoinAssay`, and `qreduceAssay`. The section on `disjoinAssay` shows a `simplify=mean` and `simplify(values)`, and I guess from that I got stuck thinking`simplify=mean` was a valid choice. Still, the example below shows `simplify` having three arguments, rather than two?

**Comment by mtmorgan** [comment]
Its trying to say that `simplify` when it is an argument to `disjoinAssay()` behaves like `mean()`, whereas when it's an argument to `qreduceAssay()` it takes three arguments. I guess these should be renamed `disjoinSimplify` and `qreduceSimplify` or similar to disambiguate.

**Comment by LiNk-NY** [comment]
I vote for `simplifyDisjoin` and `simplifyReduce` because at least they will start with `simplify`. 
Thoughts? 
@mtmorgan @lwaldron
Making changes... now :)
